ahoyapi: v2
commands:
  up:
    cmd: "docker-compose up -d"
    usage: Start the docker-compose containers.
  
  build:
    cmd: "docker-compose up -d --build"
    usage: Build and start the docker-compose containers.

  ps:
    cmd: docker-compose ps "$@"
    usage: List the running docker-compose containers.

  start:
    cmd: docker-compose start "$@"
    usage: Start the docker compose-containers.

  stop:
    cmd: docker-compose stop "$@"
    usage: Stop the docker-compose containers.

  restart:
    cmd: docker-compose restart "$@"
    usage: Restart the docker-compose containers.

  drush:
    cmd: docker-compose exec cli drush "$@"
    usage: Run drush commands in the cli service container.

  install:
    cmd: docker-compose exec cli drush si -y
    usage: Run drush site install in the cli service container.

  login:
    cmd: docker-compose exec cli drush uli
    usage: Run drush uli in the cli service container.

  cli:
    cmd: docker-compose exec cli bash
    usage: Start a shell in the container (like ssh without actual ssh).

  pull:
    cmd: docker image ls --format \"{{.Repository}}:{{.Tag}}\" | grep govcms | grep -v none | xargs -n1 docker pull | cat
